# Header
menu:
  Linux: /tags/Linux
  RT-Thread: /tags/RT-Thread
  XV6: /tags/XV6
  C Lang: /tags/Clang
  GitHub:
    url: https://github.com/luswdev
    icon: fab fa-github

# Footer
footer_menu:
  Home: /
  Archives: /archives
  Tags: /tags
  Categories: /categories
  About: /about

# Title on top left of menu. Leave empty to use main blog title
menu_title: 

# URL of the Home page image
index_cover: /img/home-bg.jpg

start_year: 2018

toc:
  enable: true
  heading: h2, h3, h4
  collapseDepth: 0
  showToggleBtn: true
b2t: true
t2b: false

# Default post title
default_post_title: Untitled

postInfo:
  wordCount: true
  min2read: false
  readCount: false

# Comments. Choose one by filling up the information
comments:
  # Disqus comments
  disqus_shortname: 
  # Facebook comments
  facebook:
    appid:
    comment_count: 5
    comment_colorscheme: light
  gitalk:
    enable: true
    owner: 'luswdev' 
    repo: 'hexo-gitalk-comment'
    oauth:
      accessToken: 'b554e5cfdb57826c448b9b147bc46ccc7a872cfb'    
      clientId: '97c34b7bba491c6a5007'
      clientSecret: '6140d208bae6bbbc69c65e3e332a46d090094fc8'
    admin: 'luswdev'

# Google Analytics Tracking ID
google_analytics: UA-158078787-1

busuanzi:
  enable: true
  cdn: //busuanzi.ibruce.info/busuanzi/2.3/busuanzi.pure.mini.js
  totalTraffic: false
  totalNumberOfvisitors: false 

# Addthis ID
addthis:

# set your own favicon
favicon: /img/favicon.png

# Social Accounts
twitter_url:
twitter_handle:
facebook_url:
github_url: https://github.com/luswdev
gitlab_url:
linkedin_url: https://www.linkedin.com/in/callum-lu-0aa77066/
mailto: info@lusw.dev

mathjax:
  enable: true
  cdn: //cdn.jsdelivr.net/npm/mathjax@2.7.5/unpacked/MathJax.js?config=TeX-AMS-MML_HTMLorMML
